### ISSUE TITLE
downloading the declutter Edit Form Script on mac 10.9.5 in FF44.0.2

### ISSUE THREAD

**Issue by Ellenvdw** [tuxfre/esko-SC-scripts#1]
Hi Benjamin :-)
tried to download the declutter Edit Form Script by clicking on the icon  (:floppy_disk:) 
but it seems to open the .js file in the browser instead.
Is this a setting in FF or has this something to do with the way the page is setup?
kr
Ellen

-> ignore this message. After reinstalling the monkey it's ok!

**Comment by tuxfre** [comment]
Hi @Ellenvdw,

Is it no longer an issue or was it an accidental close?
Let me know if I shall act. I can connect on your machine (don't post the details here, message me via Lync if needed)

**Comment by Ellenvdw** [comment]
Hi @tuxfre I already closed the case...opened it too soon. sorry. after I reinstalled the monkey it was ok. so I guess the first time I installed the monkey something must have gone wrong. 
so yes it's solved now. I have to disappoint you, as you don't need to do something for this one :-)

**Comment by tuxfre** [comment]
hi @Ellenvdw,

I can't complain of having less work to do ;)

Thanks for the update!
