### ISSUE TITLE
Wrong link for NA job folders

### ISSUE THREAD

**Issue by saco-ekso** [tuxfre/esko-SC-scripts#12]
# Esko SC Script issue
## Affected script
- Name: ServiceCloud Local Links
- Version: 8
## OS
- Name: Windows
- Version: 7 Pro SP1
- Language: US English
## Browser
- Name: Firefox
- version:45.0.1
- language (if different from OS):
## Short summary if your issue

The path in the link is \CC-SW-Problemlog-Gent\CC-SW-Problemlog-Gent. For NA is should be S:\CC-SW-Problemlog-NA
## Steps to reproduce the issue

Click on the "Job Folder Windows" link
The  location is for Gent not NA
## Other details:

**Don't hesitate to include details and screenshots.**

---

@tuxfre

**Comment by tuxfre** [comment]
Hi Sam,

I'll look into this. I'll probably go the easy way and add some option like with telescope (where you pick your server).

I'd also like to ask @korinapieters if she knows if our APAC friends have their own server as well, so I can integrate everyone for the next release.

Kind regards,

Benjamin

**Comment by tuxfre** [comment]
Hi @korinapieters,

Sorry to bug you, I know you're just back from holidays (I hope you could relax a bit) ... but are you aware of such a server as well for Asia, or maybe who I should ask for it?

Kind regards,

Benjamin

**Comment by korinapieters** [comment]
Hi @tuxfre 
There are indeed 3 servers.
Gent: \CC-SW-Problemlog-Gent\CC-SW-Problemlog-Gent
NA/LA:  \CC-SW-Problemlog-NA\CC-SW-Problemlog-NA
APAC:  \CC-SW-Problemlog-ASP\CC-SW-Problemlog-ASP

Kind regards,
Korina

**Comment by tuxfre** [comment]
Hi @korinapieters,

Thank you very very much. I'm gonna try to integrate that during the day (I have a "hole" in my planning from 12 to 13) and push the new version this afternoon.

Dear @saco-ekso, I'll let you know when the new version is online.

Thanks to both of you for your help and patience 

Kind regards,

Benjamin

**Comment by tuxfre** [comment]
Dear @saco-ekso and @korinapieters 

The script was updated (took a few commits, but last was fe83cd3357187f95c3912a350680ff114d8e57d4).

Now there is a configuration icon next to the first job folder link. It allows you to pick your server.

I quickly tested it, it seems ok. Let me know if it works.

Soon off to lunch ;)

**Comment by saco-ekso** [comment]
I just tested it and no matter with one I choose, EMEA. NALA, or APAC it still opens the folder from this server; \CC-SW-Problemlog-Gent\CC-SW-Problemlog-Gent. I will try restarting Firefox after selecting NALA and see if that helps.

**Comment by saco-ekso** [comment]
Restarting Firefox after selecting the regional server fixed it.
Thanx!

**Comment by tuxfre** [comment]
Hi Sam,

I think reloading the page would have been sufficient. I forgot to mention it (I will adapt the doc), like with all preferences, a page reload is mandatory after changing a setting.

But all in all I think it closes this log ;)
