### ISSUE TITLE
No highlight red/green anymore....  version 19

### ISSUE THREAD

**Issue by evcr** [tuxfre/esko-SC-scripts#13]
# Esko SC Script issue
## Affected script
- Name: ServiceCloud List View Highlighter
- Version: 19 
## OS
- Name: Win 
- Version: 7 prof SP 1
- Language: Eglish
## Browser
- Name: FF
- version: 54.0.1
- language (if different from OS):
## Short summary if your issue

No highlight anymore in RED and Green
![highlight](https://cloud.githubusercontent.com/assets/17274740/14316822/739d2e14-fc05-11e5-945c-66533e76d239.png)
## Other details:

**Don't hesitate to include details and screenshots.**

---

@tuxfre

**Comment by tuxfre** [comment]
Dear @evcr,

That's odd... it seems to be working over here.
![screen shot 2016-04-06 at 14 45 27](https://cloud.githubusercontent.com/assets/600530/14316947/1dd9df4e-fc06-11e5-9c40-c6e61d51547e.png)

Did you change anything (like your locale in service cloud)?

Can you also show me the date column in the capture (it's a very important one).

**Comment by evcr** [comment]
Not that I know.... If YOu want to login to take a look, give me a call...

**Comment by tuxfre** [comment]
Well, usually it's because of the date format ... so, a screencap should be enough to test my theory

**Comment by tuxfre** [comment]
No feedback, then I close.
