### ISSUE TITLE
Telescope 'traffic light' doesn't show the latest available info

### ISSUE THREAD

**Issue by Ellenvdw** [tuxfre/esko-SC-scripts#14]
# Esko SC Script issue
## Affected script
- Name: service cloud telescope status
- Version: 15 maart 2016
## OS
- Name: 10.9.5
- Version:
- Language:
## Browser
- Name: firefox
- version: 45.0.1
- language (if different from OS):
## Short summary if your issue

Telescope traffic light doesn't show the latest available info for the customer MUGLER.
## Steps to reproduce the issue

the latest report dates from 8/4/2016
http://begesesgf001.esko-graphics.com/CS-Customers-SystemInfo-Gent/MUGLER/systeminfo/html/Config_MUGLER_2016040801_018.html

while the report from 2014 is shown: http://begesesgf001.esko-graphics.com/CS-Customers-SystemInfo-Gent/MUGLER/systeminfo/html/Config_MUGLER_2014030301_001.html
## Other details:

**Don't hesitate to include details and screenshots.**

---

@tuxfre

**Comment by tuxfre** [comment]
Hi @Ellenvdw,

I think I found the (probable) cause, it seems that (Grease/Tamper)Monkey caches the redirection page's contents. So when the script asks for it again it get the cached version instead.

I have an idea for a workaround. I'll test that and let you know.

Kind regards, 

Benjamin

**Comment by tuxfre** [comment]
@Ellenvdw 

It's fixed in the ÜBER-BETA branch. You can have a look at it [here](https://github.com/tuxfre/esko-SC-scripts/raw/%C3%9CBER-BETA/ServiceCloud%20Telescope%20Status.user.js) (commit 506b317529504cb6535a05294d4e3ff863c4564f).

You can just install the beta script on top of you existing script and disable the current one in (Grease/Tamper)Monkey.

(and as a bonus, you'll get the fancy menu when clicking the customer code)

**Comment by Ellenvdw** [comment]
Great ☺ thanks
I’ll give it a try

kind regards
Ellen

---

Ellen Vandewoestyne  |  Software Support Engineer  |  Esko
For all support, visit: http://esko.com/support

[cid:image003.jpg@01D193FE.22B4B720]

**Comment by Ellenvdw** [comment]
Hi

Just installed the beta version and indeed it fixes the issue!
Thanks!

kind regards
Ellen

---

Ellen Vandewoestyne  |  Software Support Engineer  |  Esko
For all support, visit: http://esko.com/support

[cid:image003.jpg@01D194A3.451C2EB0]

**Comment by tuxfre** [comment]
So let's close!
