### ISSUE TITLE
highlighter : case viewed without colour. Should have been black.

### ISSUE THREAD

**Issue by evcr** [tuxfre/esko-SC-scripts#15]
# Esko SC Script issue
## Affected script
- Name: highlighter 
- Version:19
## OS
- Name: Windows 
- Version: 7 professional SP1
- Language: English
## Browser
- Name: Firefox 
- version: 45.0.2
- language (if different from OS): English
## Short summary if your issue

Case 619723 not highlighted in black. while logged yesterday evening at 17:20
## Other details:

**Don't hesitate to include details and screenshots.**

![case not in black](https://cloud.githubusercontent.com/assets/17274740/14976710/4a1bda4a-110e-11e6-8ffc-5ca96bbd916c.PNG)

---

@tuxfre

**Comment by tuxfre** [comment]
Hi @evcr 

I know i'm annoying with that ... but I really really really need to see the date column. I parse this date to calculate the time and if there is something weird in the date that's often the cause for highlight issues... would you mind scrolling a bit to the right and making another capture so I know what is the date format you use?

Thanks!

Benjamin

**Comment by evcr** [comment]
![case not in black_2](https://cloud.githubusercontent.com/assets/17274740/14976899/f6edb45e-110f-11e6-962c-1b509e7f44e3.PNG)

Hi Benjamin,

Sorry. Thought you only needed to see the date of my computer. And as the columns are not completely on my laptop (normally I view on the big screen), didn't take care of that... Anyhow, here is the new screendump. Thanks :-)
PS being 'annoying' as you call it is totally allowed if it brings us further :-)
Eva

**Comment by tuxfre** [comment]
Ok, now I see, the date format has no zero as starting number ... I'll have to tweak the regex for this ;)

Back to you soon with a fix.

**Comment by tuxfre** [comment]
Should be fixed by commit 506f398a9dfaebee923d1edd773c28d96a81c562.

Please update to version 20 and let me know if it's better 😉

**Comment by evcr** [comment]
You're a hero.
Solved with version 20 !!
You can close the case.
your MTTR is even getting better I guess ;-)

**Comment by tuxfre** [comment]
13 minutes between the screenshot and the fix... I ought to do better 

https://youtu.be/sEpuYFHjayw

**Comment by korinapieters** [comment]
☺

Korina Pieters  |  Service Business System Engineer  |  Esko
T. +32 (0)9 216 90 19

[Description: Description: esko-logo-mail]

Kortrijksesteenweg 1095
B-9051 Gent, Belgium
