### ISSUE TITLE
ServiceCloud Declutter Edit form/ adaptations needed for the new layout of the edit form

### ISSUE THREAD

**Issue by tuxfre** [tuxfre/esko-SC-scripts#16]
# Esko SC Script issue

## Affected script
* Name: ServiceCloud Declutter Edit form
* Version: 7

## OS
* Name: OSX
* Version: Multiple (testes by BEVI using el Capitan) 
* Language: not language-dependent 

## Browser
* Name: Safari 
* version: Version 10.0.1 (11602.2.14.0.7)
* language (if different from OS): not language-dependent

## Short summary if your issue
As reported by TD, the folding of boxes doesn't match the selected status anymore since the layout changes.

See Tom's video at https://esko.box.com/s/2cyr3dpwoqwg3faqzezhe8wz8809h8c3

## Steps to reproduce the issue
Edit a case

## Other details:
**Don't hesitate to include details and screenshots.**
Thanks TD for reporting and making a video

____
@tuxfre

**Comment by tuxfre** [comment]
made a post on the announcements page

https://github.com/tuxfre/esko-SC-scripts/wiki/Announcements#new-servicecloud-edit-form-layout

**Comment by tuxfre** [comment]
Dear @korinapieters,

Next time there is a change to the layout of the edit page being prepared, would it be possible to get an early warning (maybe a couple weeks) so I can prepare before (maybe by looking at the test system).

That would prevent the users from having to wait until I fix the issue ;)

Thanks!

**Comment by korinapieters** [comment]
Hi Benjamin,

I’m very sorry for the inconvenience.
I will keep you updated as much as possible. Unfortunately I often hear about it only some hours before… like was the case for the case page layout.

All features to be deployed still in the coming days are available on the Accept sandbox. Could you try esko.oktapreview.com and verify if you see the Salesforce Accept sandbox?

But the major changes are already deployed to live environment.

Kind regards,
Korina

Korina Pieters  |  Service Business System Engineer  |  Esko
T. +32 (0)9 216 90 19

[esko-logo-mail_2016]

Kortrijksesteenweg 1095
B-9051 Gent, Belgium
P Please don't print this e-mail unless you really need to!
www.esko.com<http://www.esko.com>  |  Facebook <https://www.facebook.com/eskocompany>  |  Blog<http://blog.esko.com/>  |  YouTube<http://www.youtube.com/eskoartwork>  |  Twitter <https://twitter.com/eskocompany>  |  LinkedIn<http://www.linkedin.com/groups?mostPopular=&gid=1028477&trk=myg_ugrp_ovr>

**Comment by korinapieters** [comment]
Hey Korina,


I hope the tone wasn't too harsh… that wasn't the intention. I know that as often as esko, it's "take it as it comes" ;)


I'll try fixing this tomorrow and then I'll have a look at the sandbox. Anything special I should pay attention to?


(side note: nice that you brought the action required toggle back to the top of the right column, I was already thinking of making a plugin to put it back up :-D)


Have a great evening!


--
Benjamin Vigier  |  Solutions Support Engineer  |  Esko


For all support, visit: http://esko.com/support














From: "Pieters, Korina" <Korina.Pieters@esko.com>
Date: Wednesday 21 December 2016 at 16:32
To: tuxfre/esko-SC-scripts <reply@reply.github.com>
Cc: "Vigier, Benjamin" <benjamin.vigier@esko.com>
Subject: RE: [tuxfre/esko-SC-scripts] ServiceCloud Declutter Edit form/ adaptations needed for the new layout of the edit form (#16)








Hi Benjamin,
 
I’m very sorry for the inconvenience.
I will keep you updated as much as possible. Unfortunately I often hear about it only some hours before… like was the case for the case page layout.
 
All features to be deployed still in the coming days are available on the Accept sandbox. Could you try esko.oktapreview.com and verify if you see
 the Salesforce Accept sandbox?
 
But the major changes are already deployed to live environment.
 
Kind regards,
Korina
 
Korina Pieters  |  Service Business System Engineer 
 |  Esko
T. +32 (0)9 216 90 19
 

 
Kortrijksesteenweg 1095
B-9051 Gent, Belgium
P
Please don't print this e-mail unless you really need to!
www.esko.com  | 
Facebook
 | 
Blog 
 |  YouTube 
 |  Twitter
 | 
LinkedIn

**Comment by tuxfre** [comment]
The script should be adapted to the new layout.
(see 6bb79d2091b61aac213cee375753e0e6726ca5ed)

Please update your scripts from the repository (if your plugin didn't do it for you)
