### ISSUE TITLE
Feature Request: ServiceCloud Declutter Edit Form for Close( to Confirm): unfold Billing Information

### ISSUE THREAD

**Issue by andsesko** [tuxfre/esko-SC-scripts#17]
# Esko SC Script issue

## Affected script
* Name: ServiceCloud Declutter Edit Form
* Version: Irrelevant

## OS
* Name: Irrelevant
* Version: Irrelevant
* Language: Irrelevant

## Browser
* Name: Irrelevant
* version: Irrelevant
* language (if different from OS): Irrelevant

## Short summary if your issue
Feature Request: ServiceCloud Declutter Edit Form for Close( to Confirm): unfold Billing Information

## Steps to reproduce the issue
-

## Other details:
I think it would be convenient to also have Billing Information visible when closing a case; so you can easily see you are not accidentally invoicing a case that should not be invoiced, or vice versa.
-> When selecting Close( to confirm), close all sections except Case Information and Solution Details (=current behaviour), and Billing information. 

Thanks to consider!
Kind Regards,

____
@tuxfre

**Comment by tuxfre** [comment]
Thanks for suggesting!

It could make sense indeed ;)
I'll have a look at that tomorrow

**Comment by tuxfre** [comment]
Hi @andsesko,

I was feeling playful 🎉  today, so I modified the code and submitted it ... without any kind of testing. (see 641345cb1ad22c96b703e7c131ca765cfa2bc7c5)
If you force your plugin to update the scripts, and refresh the page, it should be ok.

let me know if I broke it 😉

**Comment by andsesko** [comment]
So I noticed... :) 
Will have a look and let you know :)

**Comment by andsesko** [comment]
Looks OK to me!
Gracias!

**Comment by tuxfre** [comment]
If it's good enough for you, it's good enough for me 😆 

Let's close 🚪

**Comment by tuxfre** [comment]
(oh, btw, how's my response time on this one? and my mttr?)

**Comment by andsesko** [comment]
Not so good. Worrying. You are overshooting, creating an unrealistic expectation pattern with your customers :P

**Comment by tuxfre** [comment]
Sorry, I'll try meeting esko's standards next time :rofl:

**Comment by Ellenvdw** [comment]
For me you are the best.
:-p

**Comment by tuxfre** [comment]
wow, wow, wow... now that's unrealistic expectations 😆  (jk)

**Comment by andsesko** [comment]
The Russians are spying on us !

**Comment by tuxfre** [comment]
well, that's good, isn't it... means we're almost as important as The Donald

(dear Vlad, if you're reading this, big fan, please don't send me to Siberia)
