### ISSUE TITLE
Better Files Widget : When having opened a visualisation of the file, it is difficult to get back to the default case details / feed view.

### ISSUE THREAD

**Issue by evcr** [tuxfre/esko-SC-scripts#18]
# Esko SC Script issue

## Affected script
* Name: Better Files Widget
* Version: (first one released ;-) Version 1 last update 17 march

## OS
* Name: Windows 
* Version: 7 professional SPA
* Language: English

## Browser
* Name: Firefox 
* version: 52
* language (if different from OS):

## Short summary if your issue

Clicked on file to view it.
Afterwards difficult to get back to normal case feed or details view.
Wanted to makes screendump now, but seems that the plugin is not there anymore. WIll add a screendump later.

## Other details:
**Don't hesitate to include details and screenshots.**

____
@tuxfre

**Comment by tuxfre** [comment]
Hi @evcr 

Would opening the file in a new browser tab/window help? (that's the best I can come up right now)

Kr,

Benjamin

**Comment by evcr** [comment]
Hi Benjamin,

Again such a quick answer ☺

Would be great to, when clicking on the file, open it by default in a new tab, not in the window itself.

Below the promised screenshot on what I see and my findings (with current behaviour)

Apparently, at opening of the attachement, it changes the case tab to an ‘external page’ tab.
Meaning I cannot click on the different screendumps one after the other to see them enlarged.
When I go back to the case list view to open the case again, it just visualizes me the External Page tab again.
Current best solution (to me) is to write down the case nr, close the external Page tab and open it again…

[cid:image003.png@01D29F29.8874B0B0]

Kr,
Eva


Eva Creten |  Solutions Support Engineer  |  Esko

For all support, visit: http://esko.com/support

[cid:9C72BB59-1BD5-4EB0-821A-118BEA7D8B72]

**Comment by tuxfre** [comment]
Hi @evcr 

I guess if I can get it to open in a new tab then we worked around the issue ;)

(note that the screendump didn't make it into Github's ticket... so I ca only guess what you have onscreeen, could you upload it at https://github.com/tuxfre/esko-SC-scripts/issues/18?)

Kr,

**Comment by evcr** [comment]
![openeing a screenshot](https://cloud.githubusercontent.com/assets/17274740/24045190/846bd690-0b1e-11e7-9ba4-b5f1227db7a9.png)

**Comment by tuxfre** [comment]
Yup, the capture confirms that having a new tab is **the** solution.
I've added the code, I have to test it (I'm also cleaning up and documenting my code).

If it's fine on my end, then I'll upload it asap as V4.

**Comment by tuxfre** [comment]
Hi @evcr 

I pushed a new version (https://github.com/tuxfre/esko-SC-scripts/commit/6c433651b7cc093a674912fbe46324142ac3dab8) to fix this issue.

Can you update your script?

Kr,

**Comment by evcr** [comment]
Hi Benjaminj,

Uploaded v 4, and after a restart of my browser the screendumps are opened in a new tab ☺
Great !!!!!!!!

You deserve (again) a fantastic weekend ;-)
Eva

Eva Creten |  Solutions Support Engineer  |  Esko

For all support, visit: http://esko.com/support

[cid:9C72BB59-1BD5-4EB0-821A-118BEA7D8B72]

**Comment by tuxfre** [comment]
Hi @evcr 

Glad that it works!

Enjoy the weekend too.


(and let's close this issue)
