### ISSUE TITLE
Files Widget - unresponsive script

### ISSUE THREAD

**Issue by evcr** [tuxfre/esko-SC-scripts#19]
# Esko SC Script issue

## Affected script
* Name: Files Widget
* Version: 5

## OS
* Name: Windows
* Version: 7 professional SP1
* Language: English

## Browser
* Name: FF
* version: 52
* language (if different from OS): English

## Short summary if your issue
unresponsive script.
See screenshot
![files_widget_error 1](https://cloud.githubusercontent.com/assets/17274740/24151097/0bec4880-0e48-11e7-82f0-8c0619771604.png)

## Other details:
**Don't hesitate to include details and screenshots.**

____
@tuxfre

**Comment by tuxfre** [comment]
mmm... that's odd

The error would point out to jQuery itself, which is the library I use to manipulate the elements on the pages...

1.  ![download](https://cloud.githubusercontent.com/assets/600530/24151384/e7e04e68-0e48-11e7-87c8-da60da0e2b9a.jpg) (no, seriously, have you restarted Firefox?)
2. Did it happen after an upgrade of the script?
3. If you have no ServiceCould tabs open (like "00837828" in the capture), does it happen as well?
4. Can you try deleting this particular userscript and reinstalling?

I know, not very creative suggestions... but as I said, odd one.

**Comment by tuxfre** [comment]
(and if you let the script continue, does it bogs FF down?)

**Comment by tuxfre** [comment]
Hi @evcr 

Did it happen again?

**Comment by tuxfre** [comment]
Ok, no feedback, assuming the issue hasn't occurred again => closing

(can be reopened on request of @evcr)
