### ISSUE TITLE
Merging 2 chapters on https://github.com/tuxfre/esko-SC-scripts 

### ISSUE THREAD

**Issue by evcr** [tuxfre/esko-SC-scripts#2]
Can “List of currently usable scripts” and “Install and pre-requisites” chapter/ WIKI pages be merged ? They seem to contain similar info.

**Comment by tuxfre** [comment]
I can surely consider that. 
But I'm afraid that the page would become too long (if we add new scripts) and users would't read everything.
Also I believe it would be easier to point the users to the install doc if it has its own page.

What would be the rationale / use case for having everything on the same page?

**Comment by tuxfre** [comment]
Hi @evcr,

Do we still keep this one open?

**Comment by evcr** [comment]
Hi Benjamin, You can close this case

**Comment by tuxfre** [comment]
@evcr 
Ok Eva, let's close!
