### ISSUE TITLE
install link for refresh list/telescope report doesn't seem to work

### ISSUE THREAD

**Issue by Ellenvdw** [tuxfre/esko-SC-scripts#21]
# Esko SC Script issue

## Affected script
* Name: refresh list and telescope report
* Version:

## Browser
* Name: firefox 52

## Short summary if your issue
installer link doesn't work. when using the http link, it says the page is not found

f.i. https://github.com/tuxfre/esko-SC-scripts/raw/master/ServiceCloud Telescope Status.user.js "Install the script") 
<img width="789" alt="screen shot 2017-04-20 at 10 45 13 am" src="https://cloud.githubusercontent.com/assets/17617272/25221842/d95a45b2-25b6-11e7-9a24-25ca12ea8e18.png">

## Other details:
**Don't hesitate to include details and screenshots.**

____
@tuxfre

**Comment by tuxfre** [comment]
Hi @Ellenvdw 

This was just reported by Erwin as well (albeit not using the issue tracker)
I have edited the pages, so if you refresh it should be good now

Seems that GitHub had updated their markdown parser and now it doesn't tolerate whitespace in URLs anymore ...

**Comment by tuxfre** [comment]
@Ellenvdw 

Can you confirm it's now fixed on your end?

**Comment by Ellenvdw** [comment]
:-) indeed I can confirm it's working now

**Comment by Ellenvdw** [comment]
thanks

**Comment by tuxfre** [comment]
Thanks!

So let's close
