### ISSUE TITLE
Wish - Cases colored based on last contact

### ISSUE THREAD

**Issue by saco-ekso** [tuxfre/esko-SC-scripts#22]
# Esko SC Script issue

## Affected script
* Name:
* Version:

## OS
* Name:
* Version:
* Language:

## Browser
* Name:
* version:
* language (if different from OS):

## Short summary if your issue
This is a wish. We now have a script that will color cases base on how close they are to the start milestone. What we would like is a script that colors user's cases based on the last time they had an action applied to them. For example:
Case that has been acted on today - no color
Case that has not been acted on since yesterday - gray
Case that has not been acted on for two days - yellow
Case that has not been acted on longer than three days or longer - red

## Other details:
**Don't hesitate to include details and screenshots.**

____
@tuxfre

**Comment by tuxfre** [comment]
Hi @saco-ekso 

It's already weekend on this side of the pond 😉 

But I promise I'll take a look on monday.


So it's more for cases that are already in "Working" status, right?


Enjoy the weekend!

Friendly regards,

Benjamin

**Comment by saco-ekso** [comment]
Yes, that is correct, working cases.

I didn’t expect a response until Monday, go back to enjoying your weekend! ;-)

Kind regards,

Sam Cox | Application Support Specialist | Esko

**Comment by tuxfre** [comment]
Hi @saco-ekso 

## I just posted the first version.

You can install it by going to https://github.com/tuxfre/esko-SC-scripts/raw/master/ServiceCloud%20Working%20Cases%20Highlighter.user.js
I plan on adding a wiki entry at some later stage (when we're sure it works and covers your needs).

It highlights cases with status either "Working" or "Waiting" (all the waiting types) but not R&D or licensing (as these are dependent on 3rd party action).
 
Unfortunately, my personal pot doesn't cover all the cases in the wish, so I couldn't test all colours, let me know if anything is broken ;)

One last word, if you want the highlighter to work it is **mandatory** that the view you use includes the column "Last Modified Date/Time" and that has one of the supported date formats ('murrican🍔 , "belgian"🍟 , french🧀 ... but not mexican 🌮 )

Have a great day!

(I have to stop here, I think I used my emoji quota for the week)

**Comment by tuxfre** [comment]
I guess it's working good (no complains) so let's close...
