### ISSUE TITLE
Firefox Quantum

### ISSUE THREAD

**Issue by saco-ekso** [tuxfre/esko-SC-scripts#23]
# Esko SC Script issue

## Affected script
* Name: All of them
* Version: 

## OS
* Name: Windows
* Version: 7
* Language: English

## Browser
* Name: Firefox Quantum
* version: 57.0
* language (if different from OS):

## Short summary if your issue
Scripts no longer work. 

## Other details:
**Don't hesitate to include details and screenshots.**
There are recommendations to get them to possibly work and was wondering if I should use any:  Greasemonkey 4 For Users
As mentioned in the main post, Greasemonkey 4 is changing how it runs user scripts.  Many user scripts will continue to run as expected, but this will break some scripts.  If you rely on such scripts, you might want to install **Violentmonkey** or **Tampermonkey**, both of which provide better compatibility for existing scripts.
Scripts
If you'd prefer to stick with Greasemonkey, you'll need to wait for the script to be updated to be compatible.  Find the original author of your script, and ask them to update for Greasemonkey 4 compatibility.  Referencing this post may help.  And please know that we'll continue working to improve further and further as time goes on!

____
@tuxfre

**Comment by tuxfre** [comment]
Hi @saco-ekso,

_[note that I'm off work at least until the 22-nov-17]_

The quickest thing to get the scripts working in Quantum is indeed to use Greasemonkey as suggested by GM's authors.

To be honest, their decision to break backward compatibility with older userscripts is quite risky... lots of (non-esko) scripts aren't maintained anymore and that could drive users to other extensions.

We'd have to assess the overall impact of having users witch to Tampermonkey vs the work needed to adapt the extensions (and if that adapatation wouldn't break the compatibility with other extensions/browsers).

I think I'd have to discuss that with @korinapieters  and Peter (PEMY) when I'll be back in the office. That will require time and I'd rather get Peter's approval before starting any major rewrite.

In the meantime, head to https://addons.mozilla.org/en-US/firefox/addon/tampermonkey/ and install it, then come back to the wiki on Github and reinstall the scripts by clicking the 💾 . I'm sorry for the inconvenience... I didn't see this one coming 😞 

Have a great day!

**Comment by tuxfre** [comment]
I think we can all agree that Tampermonkey makes a good alternative ... so I'll close this
