### ISSUE TITLE
Job folder link not working

### ISSUE THREAD

**Issue by saco-ekso** [tuxfre/esko-SC-scripts#24]
# Esko SC Script issue

## Affected script
* Name: ServiceCloud Local links
* Version: latest

## OS
* Name: Windows 10 Pro
* Version: 10
* Language: English

## Browser
* Name: Firefox
* version: 52.5.3
* language (if different from OS):

## Short summary if your issue

My hard drive failed and it was replaced. Once I reinstalled the Esko SC Scripts the link to the Job folder does not work. I did configure it to connect to NALA. When you click on the link the path does show as the bottom of the screen but nothing happens.

## Steps to reproduce the issue
Click on the link to the job folder and nothing happens

## Other details:
**Don't hesitate to include details and screenshots.**

____
@tuxfre

**Comment by tuxfre** [comment]
Hi @saco-ekso 

Maybe check what we had done in [issue 11](https://github.com/tuxfre/esko-SC-scripts/issues/11). You can also follow the steps at https://github.com/tuxfre/esko-SC-scripts/wiki/*-Scripts-*-Local-Links#notes-regarding-firefox (Firefox actually protects you against script accessing your local hard drive, so we have to cheat a bit).

Good luck

(I expect to be back on duty on the 19th of January)

**Comment by saco-ekso** [comment]
Hi Benjamin,
That didn't solve the issue this time in Windows 10 and Firefox 52.5.3. I already had the script installed when I added the user file but I did run the installer for the script again but that didn't help either. No rush, this can wait until you return on the 16th.
Thanx,
Sam

**Comment by tuxfre** [comment]
Hi @saco-ekso 

In which folder (can you copy the path here) did you copy the user.js file? (can you copy/paste the full path here?)

Also, I'm sorry to tell that I don't have Win 10 for testing ... so I could have some issues reproducing.
Do you know if anyone else uses Win 10 and what their experience was?

Regards,
Benjamin

**Comment by saco-ekso** [comment]
Here's where I copied it to: 
C:\Users\saco\AppData\Roaming\Mozilla\Firefox\Profiles\s34mm96o.default

**Comment by tuxfre** [comment]
yup, that's the good location 🙁 
so we have another issue here

did you check if the file:// protocol isn't already associated to some other application?

**Comment by saco-ekso** [comment]
How do I check to protocol?

**Comment by tuxfre** [comment]
1. go to the "Applications" section of the option panel
(you can type about:preferences#applications in the address bar
2. use the search file to filter on "file"
3. make sure it's set to "Use Windows Explorer"

(sorry for the incomplete post earlier, my finger slipped)

**Comment by saco-ekso** [comment]
Nope, no association set up for file://

**Comment by tuxfre** [comment]
and if you manually set it to the windows explorer?

**Comment by saco-ekso** [comment]
file:// doesn't show in the list.
![applications](https://user-images.githubusercontent.com/18007911/34784256-c7499e66-f5fb-11e7-8e3b-064121cd8139.png)

**Comment by tuxfre** [comment]
huh... 
And you're using FF57 (aka Quantum)?

Seems it requires extra steps as described in the solution at https://support.mozilla.org/en-US/questions/1185059

**Comment by saco-ekso** [comment]
I have version 52.5.3 ESR installed.

I did find a way to get it to work. I installed the IE Tab extension
![image](https://user-images.githubusercontent.com/18007911/34796861-f823814a-f624-11e7-92f3-05db1d1b1176.png)
And now I can right click on the Job Folder link and choose "Open Link in Ext.App" and it does open the folder. 
![image](https://user-images.githubusercontent.com/18007911/34797228-c316b02a-f625-11e7-9aee-8e596fa8017e.png)

**Comment by saco-ekso** [comment]
I'm guessing it's a Windows 10 issue. My colleague who is running Windows 7 was having the same problem so I sent him your instructions and it fixed it for him.

**Comment by tuxfre** [comment]
Hi Sam,

Glad that you could find a workaround... it's a bit the nuclear warhead to kill a fly, but as long as it works ;)

Indeed it would seem that Win 10 may have introduced new issues with regards to opening local files from a browser (again, from a security perspective, it makes sense to prevent web page from accessing local data)

If I get my hands on a Win 10 VM, I'll do some tests, but in the meantime, I suggest closing this case.

**Comment by saco-ekso** [comment]
That sounds good. Let me know what you find out about Windows 10.

**Comment by tuxfre** [comment]
Will do!
