### ISSUE TITLE
Feature Request: ServiceCloud Declutter Edit Form for Send to R&D / Send to Licensing

### ISSUE THREAD

**Issue by andsesko** [tuxfre/esko-SC-scripts#4]
# Esko SC Script issue
## Other details:

ServiceCloud Declutter Edit Form looks like a nice tool (like all scripts shown :) ). 
Any chance of extending it 
1/ not only for closing (which is obviously the most used "Edit" use case) but also for Send to R&D and Send to Licensing 
and 
2/ Pre-Fill in the Status field
? 

I assume the trigger to decide which section to open would require additional buttons, so not sure if that's feasible at all. Ideally, I'd think there would be 3 (4) buttons: 
1) Close:
- Close all sections except Case Information and Solution Details (=current behaviour)
  (- Pre-select Status: Closed)

2) Send to R&D
- Close all sections except Case Information and Global Support - R&D Information 
  (- Pre-select Status: Sent to R&D)

3) Send to Licensing:
- Close all sections except Case Information and License Information
  (- Pre-select Status: Sent to Licensing)

(4) Close to Confirm:
- Close all sections except Case Information and Solution Details (=current behaviour)
  (- Pre-select Status: Close to Confirm))

Thanks for considering!
Kind Regards,
Andy

@tuxfre

**Comment by tuxfre** [comment]
Hi @andsesko,

I'm not sure buttons are possible, but I could "maybe" try to capture the value of the "Status" field 
![screen shot 2016-03-10 at 19 25 03](https://cloud.githubusercontent.com/assets/600530/13679787/d6b40e16-e6f5-11e5-9430-06de36ff0e86.png)

And fold/unfold sections based on the scenario you suggest.

I'd have to estimate the effort required, I guess I'd need between 0,5 and 1 day, but I need to check in details. Would probably require to rewrite the script using a function to which I'd pass what to hide as arguments.

But that's a nice feature request :+1:

**Comment by andsesko** [comment]
Hi @tuxfre ,

No problem, I'm just suggesting. Up to you to see if it is feasible/desirable/worth the effort.

Cheers,
Andy

**Comment by tuxfre** [comment]
Hi @andsesko,

I just pushed an updated version (v6) that now checks the value of the "status" field (
![screen shot 2016-03-16 at 15 36 27](https://cloud.githubusercontent.com/assets/600530/13815972/ea36613c-eb8c-11e5-8212-50821cdd35be.png)) and folds/unfolds sections depending on that.
This means that for example, when you pick "Sent to License", you'll see only the sections "Case Information" and "License Information", all the rest will be folded.

It also comes with an exciting and innovative new feature. When a section is folded, its fold/unfold link will display [+] whereas when it's unfolded the link will display [-].

Let me know if it works and if it somehow answers to your feature request.

Regards,

Benjamin

**Comment by tuxfre** [comment]
Announcement officially posted, see [Declutter updated](https://github.com/tuxfre/esko-SC-scripts/wiki/Announcements#declutter-updated)

**Comment by andsesko** [comment]
You @tuxfre , Sir, are a star :o) 

However one thing I noticed (just had a quick look): when I choose Sent to R&D, it unfolds "Description Information". "Global Support - R&D Information" would suite me better... (FF on Mac). Need to test more, or can you see what's wrong there? 

Kind Regards,
Andy

**Comment by tuxfre** [comment]
Hi @andsesko 

Indeed, you're 101% right on this. It's a bug, I'm gonna fix this right now.
It's intended to work in the way you describe. If I'm luck it's just a copy/paste error, if not, more work will be needed.

Kind regards,
Benjamin

**Comment by tuxfre** [comment]
Hi @andsesko 

Should be fixed, right now, by version 7 :wink:

**Comment by andsesko** [comment]
Hi @tuxfre ,

That looks nice indeed :o) 
Thanks you!

Will keep an eye on it, will let you know if I would notice anything unexpected (but not expecting any ;o) ).

Kind Regards,
Andy

**Comment by tuxfre** [comment]
@andsesko, I'm sure that if I forgot anything you'll spot it :wink: 

if there's no issue before the weekend, we'll just close the issue (we can reopen if needed or create a new ticket)
