### ISSUE TITLE
Telescope Status - NA - wrong link

### ISSUE THREAD

**Issue by LynneJ** [tuxfre/esko-SC-scripts#5]
# Esko SC Script issue
## Short summary if your issue:

link not correct for NA telescope data
## Steps to reproduce the issue:

get telescope info from NA customer D01025 - see case 00601455
## Other details:

Link the shows when I get data -
egwusms003.esko-graphics.com/CS-Customers-SystemInfo-Vandalia/D01025/systeminfo/html
![telescope_status-2](https://cloud.githubusercontent.com/assets/17769198/13679023/47318ba8-e6b7-11e5-8c0b-7672f6d5502e.jpg)

Don't hesitate to include details and screenshots.
![telescope_status](https://cloud.githubusercontent.com/assets/17769198/13678802/3b5f0e0a-e6b6-11e5-97a9-794e3e89259c.jpg)

@tuxfre

**Comment by tuxfre** [comment]
Hi @LynneJ,

Just one question, are all US-based customers on this server? Or is it a server for the US-based CS team?

I'm not familiar with the North-Amercian org, so please excuse the silly questions :innocent:

**Comment by LynneJ** [comment]
I believe all of the telescope data for NA is on that server.

Lynne Johnson  |  Application Support Specialist  |  Esko

For all support, visit: www.esko.com/en/Support/http://www.esko.com/en/Support/

**Comment by tuxfre** [comment]
Hi @LynneJ 

I'm going to have a look at the NA telescope, and see how I can detect a report is on there.

I'll keep you updated in here

Have great weekend!

Benjamin

**Comment by tuxfre** [comment]
@LynneJ 

One last question, are all the NA customer IDs in the form DXXXXX (where XXXXX is a number)?

Because I could maybe use that to easily distinguish the reports that are on the NA server.

**Comment by LynneJ** [comment]
No, it’s a mess.
Prepress customers start with D
Kongburg table start with S
Artios customers start with A
HP press sites start with N

If they have all of the above – it could be any of them??
Lynne Johnson  |  Application Support Specialist  |  Esko

For all support, visit: www.esko.com/en/Support/http://www.esko.com/en/Support/

**Comment by tuxfre** [comment]
Thanks @LynneJ!

Of course, if it had been easy and simple it wouldn't have been fun :smile: 
But if they follow some kind of YXXXXX where Y is either D, S, A or N... that's fine by me, I can use this as a starting point.

I'm fighting a date format issue with the highlighter and I'll have a look at how I can work with the telescope server (probably next week).

Have a great weekend!

Benjamin

**Comment by LynneJ** [comment]
They are all 6 characters at least.

Thanks for all the hard work on these tools!

Lynne Johnson  |  Application Support Specialist  |  Esko

For all support, visit: www.esko.com/en/Support/http://www.esko.com/en/Support/

**Comment by korinapieters** [comment]
Hi Benjamin,
Same issue has been reported by our test user from Singapore.
Could you maybe consider making it a setting? By default 'Gent', but allowing the user to specify the server name that they work with, such as 'Vandalia' ?

Kind regards,
Korina

**Comment by tuxfre** [comment]
Hi @korinapieters 

Do you know who could provide me with a list of all the "servers" for Telescope? Because indeed this fix would be easy to implement the way you describe. A simple drop down in the config allowing to choose between North America, Asia and Europe ...

**Comment by tuxfre** [comment]
Dear @LynneJ and @korinapieters,

I have just pushed an updated version (v4) that works using an extra preference to define which server to look at:
![screen shot 2016-03-14 at 14 56 08](https://cloud.githubusercontent.com/assets/600530/13746761/2730da7a-e9f5-11e5-8e93-012671b7f6f4.png)

Depending on browser/extension settings, and on caching the script may take up to 24h to update on your machine.

**Once updated, by default the system uses the european server.
If you want to change the server you have to go to the preferences of the userscript, select your server in the dropdown list, click save, then click close and finally force a refresh of the page (CTRL+R or CMD+R).**

Could you please let me know if this works?

**Comment by tuxfre** [comment]
By the way, the info was published on the new ["Announcements" wiki page](https://github.com/tuxfre/esko-SC-scripts/wiki/Announcements#telescope-status-updated).

Don't hesitate to check this new page from time to time for updates and infos about the whole scripting project.

**Comment by LynneJ** [comment]
This works great!

Thanks so much.

Lynne Johnson  |  Application Support Specialist  |  Esko

For all support, visit: www.esko.com/en/Support/http://www.esko.com/en/Support/

**Comment by tuxfre** [comment]
There was a last (little) change, the labels were adapted to be more generic and cover all the regions:
![screen shot 2016-03-14 at 16 04 24](https://cloud.githubusercontent.com/assets/600530/13748777/8dff1ac4-e9fe-11e5-80fc-09c47fa7292b.png)

This means current version on the repo is now v5.

As always, if I broke something in the process, just let me know :wink:

**Comment by tuxfre** [comment]
I think we all agree that the setting did the trick.
So i'm closing this issue now

**Comment by LynneJ** [comment]
I love it!

Lynne Johnson  |  Application Support Specialist  |  Esko

For all support, visit: www.esko.com/en/Support/http://www.esko.com/en/Support/
