### ISSUE TITLE
Highlighter not completely working anymore. See screendump.

### ISSUE THREAD

**Issue by evcr** [tuxfre/esko-SC-scripts#8]
![issue_highlight](https://cloud.githubusercontent.com/assets/17274740/13915226/b0a9beda-ef53-11e5-8770-cf49b1bad5ce.png)
# Esko SC Script issue
## Affected script
- Name: highlighter 
- Version: version 18
## OS
- Name: Windows 
- Version: 7 professional SP1
- Language: English
## Browser
- Name: FF
- version: 44.0.2
- language (if different from OS):
## Short summary if your issue

See screendump. No red/grey highlight . See screendump
## Other details:

**Don't hesitate to include details and screenshots.**

---

@tuxfre

**Comment by tuxfre** [comment]
Hi @evcr,

That's odd... seems to be working over here.

Can I see the way your date is formatted? (just capture the end of the line)

Thanks

**Comment by tuxfre** [comment]
Dear @evcr 

I may have an idea, I believe you're using a date format that has no padding zero four hours (meaning 09:05 is written 9:05).

I pushed a new version (v19) some seconds ago, commit 84e1fad081a4d0db28c80df401b30de55f5aea6a.

It should make it better for you.

Kr,

Benjamin

**Comment by tuxfre** [comment]
Hi @evcr 

Can you confirm that v19 helps?

**Comment by evcr** [comment]
Sorry didn't have time yet.
Yes absolutely ! You can close the case.
V19 works !
Thanks Benjamin !!!!
