### ISSUE TITLE
Job FOlder links have been modified to smb://CC-SW-Problemlog-Gent/CC-SW-Problemlog-Gent

### ISSUE THREAD

**Issue by andsesko** [tuxfre/esko-SC-scripts#9]
# Esko SC Script issue
## Affected script
- Name: ServiceCloud Local Links
- Version: 7
## OS
- Name: Mac
- Version: 10.9.5
- Language: Irrelevant
## Browser
- Name: FireFox
- version: 44.0.2
- language (if different from OS): -
## Short summary if your issue

To overcome connection issues to smb://esko-graphics.com/globalstorage/CC-SW-Problemlog-Gent - like many of us had on Mac), IT has replaced the JobFolder Mac & Windows using a new logical name "CC-SW-Problemlog-Gent", so:
smb://CC-SW-Problemlog-Gent/CC-SW-Problemlog-Gent/00605000-00605999/00605151
file://CC-SW-Problemlog-Gent/CC-SW-Problemlog-Gent/00605000-00605999/00605151
As a consequence, this script fails to resolve the link OK (at least on my Mac, but that could also be because I again don't have access to smb://esko-graphics.com/globalstorage/CC-SW-Problemlog-Gent).
## Steps to reproduce the issue

Click the Job Folder link.
## Other details:

Note, Also JDF URLs will have to be adjusted (IT- work), and Poolserver mapped network drives & Containers (Poolbabes). I'll inform both.

---

@tuxfre

**Comment by tuxfre** [comment]
Hi @andsesko,

I just got a mail from @korinapieters telling me as well. I'll have to adapt the script. Maybe this afternoon.
I'm currently fighting the skills matrix, it may take some time.

**Comment by tuxfre** [comment]
@andsesko & @korinapieters 

I just pushed a new version (v8) (see b3d475140439821dbcef28e125281b97fcceaed5).

Tried it quickly on my machine (OSX, with Safari) and it seems ok. Can you confirm?

Thanks

**Comment by korinapieters** [comment]
Hi Benjamin,

I installed the new version but as I use Google Chrome (and not Firefox) the Local Link script doesn’t work.
When I click the link nothing happened.

[cid:image003.png@01D1843B.8C671DC0]

The jobfolder link itself I copy pasted to Windows Explorer and this works!

Kr,
Korina

Korina Pieters  |  Service Business System Engineer  |  Esko
T. +32 (0)9 216 90 19

[Description: Description: esko-logo-mail]

Kortrijksesteenweg 1095
B-9051 Gent, Belgium

**Comment by andsesko** [comment]
@tuxfre & @korinapieters ,

Works OK, thanks for the swift action! 

Kind Regards,
Andy

**Comment by tuxfre** [comment]
@korinapieters 

Please remember that due to Chrome's security model, the support for the local links in Chrome comes with some limitations (see [Notes Regarding Google Chrome](https://github.com/tuxfre/esko-SC-scripts/wiki/*-Scripts-*-Local-Links#notes-regarding-google-chrome)).

Try installing the "[LocaLinks](https://chrome.google.com/webstore/detail/locallinks/fkkidcgelfcjmebocoaicnelkbnpgpmm)"extension and see if, at least, it shows the correct folder.

**Comment by korinapieters** [comment]
Hi Benjamin,

Yes, it does show the correct folder. This is tested ☺.

Kr,
Korina

Korina Pieters  |  Service Business System Engineer  |  Esko
T. +32 (0)9 216 90 19

[Description: Description: esko-logo-mail]

Kortrijksesteenweg 1095
B-9051 Gent, Belgium

**Comment by tuxfre** [comment]
@korinapieters 
ok, so it's limited by Chrome.
I fear there is nothing else I can do, unfortunately :cry:. Unless esko decides to create their own build of Chromium without this security feature.

So let's close this issue!

**Comment by korinapieters** [comment]
Sure!
Thanks for looking into this.

Korina Pieters  |  Service Business System Engineer  |  Esko
T. +32 (0)9 216 90 19

[Description: Description: esko-logo-mail]

Kortrijksesteenweg 1095
B-9051 Gent, Belgium
